// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Log.proto

package utility;

public final class Log {
  private Log() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class LogEntry extends
      com.google.protobuf.GeneratedMessage {
    // Use LogEntry.newBuilder() to construct.
    private LogEntry() {
      initFields();
    }
    private LogEntry(boolean noInit) {}
    
    private static final LogEntry defaultInstance;
    public static LogEntry getDefaultInstance() {
      return defaultInstance;
    }
    
    public LogEntry getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return utility.Log.internal_static_serialization_LogEntry_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return utility.Log.internal_static_serialization_LogEntry_fieldAccessorTable;
    }
    
    // required string dbId = 1;
    public static final int DBID_FIELD_NUMBER = 1;
    private boolean hasDbId;
    private java.lang.String dbId_ = "";
    public boolean hasDbId() { return hasDbId; }
    public java.lang.String getDbId() { return dbId_; }
    
    // required int64 messageId = 2;
    public static final int MESSAGEID_FIELD_NUMBER = 2;
    private boolean hasMessageId;
    private long messageId_ = 0L;
    public boolean hasMessageId() { return hasMessageId; }
    public long getMessageId() { return messageId_; }
    
    // required string key = 3;
    public static final int KEY_FIELD_NUMBER = 3;
    private boolean hasKey;
    private java.lang.String key_ = "";
    public boolean hasKey() { return hasKey; }
    public java.lang.String getKey() { return key_; }
    
    // required string operation = 4;
    public static final int OPERATION_FIELD_NUMBER = 4;
    private boolean hasOperation;
    private java.lang.String operation_ = "";
    public boolean hasOperation() { return hasOperation; }
    public java.lang.String getOperation() { return operation_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasDbId) return false;
      if (!hasMessageId) return false;
      if (!hasKey) return false;
      if (!hasOperation) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasDbId()) {
        output.writeString(1, getDbId());
      }
      if (hasMessageId()) {
        output.writeInt64(2, getMessageId());
      }
      if (hasKey()) {
        output.writeString(3, getKey());
      }
      if (hasOperation()) {
        output.writeString(4, getOperation());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasDbId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getDbId());
      }
      if (hasMessageId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, getMessageId());
      }
      if (hasKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getKey());
      }
      if (hasOperation()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getOperation());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static utility.Log.LogEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static utility.Log.LogEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static utility.Log.LogEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static utility.Log.LogEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static utility.Log.LogEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static utility.Log.LogEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static utility.Log.LogEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static utility.Log.LogEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static utility.Log.LogEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static utility.Log.LogEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(utility.Log.LogEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private utility.Log.LogEntry result;
      
      // Construct using utility.Log.LogEntry.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new utility.Log.LogEntry();
        return builder;
      }
      
      protected utility.Log.LogEntry internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new utility.Log.LogEntry();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return utility.Log.LogEntry.getDescriptor();
      }
      
      public utility.Log.LogEntry getDefaultInstanceForType() {
        return utility.Log.LogEntry.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public utility.Log.LogEntry build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private utility.Log.LogEntry buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public utility.Log.LogEntry buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        utility.Log.LogEntry returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof utility.Log.LogEntry) {
          return mergeFrom((utility.Log.LogEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(utility.Log.LogEntry other) {
        if (other == utility.Log.LogEntry.getDefaultInstance()) return this;
        if (other.hasDbId()) {
          setDbId(other.getDbId());
        }
        if (other.hasMessageId()) {
          setMessageId(other.getMessageId());
        }
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasOperation()) {
          setOperation(other.getOperation());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setDbId(input.readString());
              break;
            }
            case 16: {
              setMessageId(input.readInt64());
              break;
            }
            case 26: {
              setKey(input.readString());
              break;
            }
            case 34: {
              setOperation(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string dbId = 1;
      public boolean hasDbId() {
        return result.hasDbId();
      }
      public java.lang.String getDbId() {
        return result.getDbId();
      }
      public Builder setDbId(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDbId = true;
        result.dbId_ = value;
        return this;
      }
      public Builder clearDbId() {
        result.hasDbId = false;
        result.dbId_ = getDefaultInstance().getDbId();
        return this;
      }
      
      // required int64 messageId = 2;
      public boolean hasMessageId() {
        return result.hasMessageId();
      }
      public long getMessageId() {
        return result.getMessageId();
      }
      public Builder setMessageId(long value) {
        result.hasMessageId = true;
        result.messageId_ = value;
        return this;
      }
      public Builder clearMessageId() {
        result.hasMessageId = false;
        result.messageId_ = 0L;
        return this;
      }
      
      // required string key = 3;
      public boolean hasKey() {
        return result.hasKey();
      }
      public java.lang.String getKey() {
        return result.getKey();
      }
      public Builder setKey(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasKey = true;
        result.key_ = value;
        return this;
      }
      public Builder clearKey() {
        result.hasKey = false;
        result.key_ = getDefaultInstance().getKey();
        return this;
      }
      
      // required string operation = 4;
      public boolean hasOperation() {
        return result.hasOperation();
      }
      public java.lang.String getOperation() {
        return result.getOperation();
      }
      public Builder setOperation(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasOperation = true;
        result.operation_ = value;
        return this;
      }
      public Builder clearOperation() {
        result.hasOperation = false;
        result.operation_ = getDefaultInstance().getOperation();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:serialization.LogEntry)
    }
    
    static {
      defaultInstance = new LogEntry(true);
      utility.Log.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:serialization.LogEntry)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_serialization_LogEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_serialization_LogEntry_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017proto/Log.proto\022\rserialization\"K\n\010LogE" +
      "ntry\022\014\n\004dbId\030\001 \002(\t\022\021\n\tmessageId\030\002 \002(\003\022\013\n" +
      "\003key\030\003 \002(\t\022\021\n\toperation\030\004 \002(\tB\016\n\007utility" +
      "B\003Log"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_serialization_LogEntry_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_serialization_LogEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_serialization_LogEntry_descriptor,
              new java.lang.String[] { "DbId", "MessageId", "Key", "Operation", },
              utility.Log.LogEntry.class,
              utility.Log.LogEntry.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
